version: "3.8"

services:
  # --- BASES DE DATOS ---

  postgres-auth:
    image: postgres:15
    container_name: postgres_auth
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Hola.123#
      POSTGRES_DB: auth-db
    ports:
      - "5433:5432"
    networks:
      - delivereats-network

  postgres-restaurant:
    image: postgres:15
    container_name: postgres_restaurant
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Hola.123#
      POSTGRES_DB: restaurant-db
    ports:
      - "5434:5432"
    networks:
      - delivereats-network

  postgres-order:
    image: postgres:15
    container_name: postgres_order
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Hola.123#
      POSTGRES_DB: order-db
    ports:
      - "5435:5432"
    networks:
      - delivereats-network

  # --- MICROSERVICIOS ---

  auth-service:
    image: pampam4188/delivereats-auth-service
    container_name: auth_service_container
    ports:
      - "50051:50051"
    environment:
      DB_HOST_AUTH: postgres-auth
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: Hola.123#
      DB_NAME_AUTH: auth-db
    depends_on:
      - postgres-auth
    networks:
      - delivereats-network

  restaurant-service:
    image: pampam4188/delivereats-restaurant-service
    container_name: restaurant_service_container
    ports:
      - "50052:50052"
    environment:
      DB_HOST_REST: postgres-restaurant
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: Hola.123#
      DB_NAME_REST: restaurant-db
    depends_on:
      - postgres-restaurant
    networks:
      - delivereats-network

  order-service:
    image: pampam4188/delivereats-order-service
    container_name: order_service_container
    ports:
      - "50053:50053"
    environment:
      DB_HOST_ORDER: postgres-order
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: Hola.123#
      DB_NAME_ORDER: order-db
    depends_on:
      - postgres-order
    networks:
      - delivereats-network

  api-gateway:
    image: pampam4188/delivereats-api-gateway
    container_name: api_gateway_container
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - restaurant-service
      - order-service
    networks:
      - delivereats-network

networks:
  delivereats-network:
    driver: bridge